#!/bin/bash
export PATH=$PATH:/usr/local/mysql/bin
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/texbin
export PATH=$PATH:/usr/local/share/npm/bin
export PATH=$PATH:/usr/local/sml/bin
export PATH=$PATH:/usr/games/bin
export PATH=$PATH:/Applications/Postgres93.app/Contents/MacOS/bin
export HISTCONTROL=ignoredups
# export PERL5LIB="/Users/mmcclimon/perl5/test/lib/perl5/site_perl"

export CLICOLOR=1
export LSCOLORS="gxexcxdxbxegedabagacGg"

export IRCNICK=mmcclimon
export IRCSERVER=irc.freenode.net

export EDITOR="vim"
export ALTERNATE_EDITOR=''

export SCALA_HOME=/usr/local/scala
export PATH=$PATH:$SCALA_HOME/bin


# aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias gs='git status -sb'
alias gd='git diff'
alias gc='git commit'
alias ga='git add'
alias ld='cd ~-'
alias gvim="mvim"
alias pavan='ssh mjmcclim@pavan.music.indiana.edu'
alias medley='ssh mjmcclim@medley.music.indiana.edu'
alias ec='emacsclient -n'
alias ecc='emacsclient -c -n'
alias mvc='mvim --servername mvim --remote-silent'
alias mvcc='mvim --servername mvim'
alias latexwatch='latexmk -xelatex -pvc'

# put this in a function, since I don't use RVM a lot
start_rvm() { source ~/.rvm/scripts/rvm; }


# in a git repo, show git info in prompt
__prompt_info() {
    # colors for prompt
    local reset="\[\e[0m\]"
    local prompt_c="\[\e[38;5;074m\]"
    local dir_c="\[\e[38;5;237m\]"

    local p_open="\n${prompt_c}(\t)${reset} ${dir_c}\w${reset}"
    local p_close="\n${prompt_c}\$${reset} "

    # git info
    local p_git=''
    local gitdir=$(git rev-parse --git-dir 2> /dev/null)
    if [ -n "$gitdir"  ]; then
        local branch_c="\[\e[38;5;023m\]"
        local sha1_c="\[\e[38;5;022m\]"
        local status_c="\[\e[38;5;009m\]"

        local p_left="${dir_c}[${normal}"
        local p_mid="${dir_c}|${normal}"
        local p_right="${dir_c}]${normal}"

        local git_branch=$(git symbolic-ref HEAD 2> /dev/null | cut -d '/' -f 3)
        local p_branch="${branch_c}${git_branch}${normal}"

        local git_sha=$(git rev-parse --short HEAD 2> /dev/null)
        local p_sha="${sha1_c}${git_sha}${normal}"

        local git_status=$(git status --porcelain 2> /dev/null)
        local p_status=''
        if [ -n "$git_status" ]; then
            p_status="${status_c}*${normal}"
        fi

        p_git=" ${p_left}${p_branch}${p_mid}${p_sha}${p_right}${p_status}"
    fi

    PS1="${p_open}${p_git}${p_close}"
}

PROMPT_COMMAND='__prompt_info'


if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
fi

start_rvm

export PERLBREW_ROOT=~/.perl5/perlbrew
source ~/.perl5/perlbrew/etc/bashrc
