set guioptions-=T
set guioptions-=L
set guioptions-=r
set guioptions-=m

if has("macunix")
    set guifont=Consolas:h11
elseif has("unix")
    set guifont=Consolas\ 8
endif

" vertical guide
set cc=78

"nerdtree
nnoremap <F8> :TagbarToggle<CR>
nnoremap <F5> :NERDTreeToggle<CR>

function EmbiggenFont()
    set guifont=Ubuntu\ Mono:h16
endfunction

command Embiggen call EmbiggenFont()

"color railscasts
