vim9script

set guioptions-=T
set guioptions-=L
set guioptions-=r
set guioptions-=m

if has("macunix")
    set guifont=BerkeleyMono-Regular:h10
    set linespace=2
elseif has("unix")
    set guifont=Consolas\ 8
endif

# vertical guide
hi ColorColumn guibg=#2d2d2d
&colorcolumn = join(range(81, 999), ",")

# Don't do funny business with the cursor
set guicursor+=n:blinkon0
