LIB_PATH=$HOME/.zsh

# make sure the path gets set first
source $LIB_PATH/path.zsh

source $LIB_PATH/aliases.zsh
source $LIB_PATH/completion.zsh
source $LIB_PATH/functions.zsh
source $LIB_PATH/key-bindings.zsh
source $LIB_PATH/misc.zsh
source $LIB_PATH/prompt.zsh
source $LIB_PATH/termsupport.zsh

# yes, print a bear on new shells.
print_bear

autoload -U compinit
compinit -C
